import '../util/format.dart';
import 'models.dart';

class SeedData {
  // Open the demo signed in as the primary leaseholder (Maya).
  static Session session() => Session(userId: 'u1');

  static Property property() => Property(
        id: 'p1',
        address: '12 Marrickville Road, Marrickville NSW 2204',
        type: 'House',
        bedrooms: 4,
        bathrooms: 2,
        features: {
          'parking': true,
          'laundry': true,
          'dishwasher': true,
          'aircon': true,
          'backyard': true,
        },
        agent: 'Harbourside Property Group',
        agentContact: 'lettings@harbourside.com.au',
        leaseStart: '2025-09-01',
        leaseEnd: '2026-08-31',
        rentAmount: 980,
        rentCadence: 'weekly',
        rentStartDate: '2025-09-01',
        bondWeeks: 4,
        advanceWeeks: 2,
        maxOccupants: 5,
        setupComplete: true,
      );

  // 1 platform admin + 2 leaseholders + 3 tenants.
  static List<User> users() => [
        User(
          id: 'u0',
          name: 'Homies Admin',
          initials: 'HA',
          role: 'admin',
          email: 'admin@homies.app',
          phone: '0400 000 000',
          member: false,
        ),
        User(
          id: 'u1',
          name: 'Maya Chen',
          initials: 'MC',
          role: 'leaseholder',
          email: 'maya.chen@example.com',
          phone: '0412 334 556',
          moveInDate: '2025-09-01',
          bondPaid: true,
          bondAmount: 784,
          docVerified: true,
          advanceRentPaid: true,
          acceptedRulesAt: '2025-09-01T09:00:00.000',
          lifestyle: Lifestyle(
            smoking: 'non-smoker',
            alcohol: 'social',
            drugs: 'no',
            relationship: 'relationship',
            pets: 'none',
            schedule: 'early-bird',
            guests: 'sometimes',
            cleanliness: 'very-tidy',
            diet: 'vegetarian',
            occupation: 'UX designer',
          ),
          emergency: EmergencyContact(name: 'Grace Chen', relationship: 'Sister', phone: '0412 998 221'),
          // Already verified by the admin.
          leaseVerification: LeaseVerification(
            fullName: 'Maya Chen',
            phone: '0412 334 556',
            email: 'maya.chen@example.com',
            agreement: Attachment(fileName: 'lease-marrickville.pdf', type: 'application/pdf', size: 248000),
            status: 'verified',
            submittedAt: '2025-08-25T10:00:00.000',
            reviewedAt: '2025-08-26T14:20:00.000',
          ),
        ),
        User(
          id: 'u2',
          name: 'Daniel Okafor',
          initials: 'DO',
          role: 'leaseholder',
          email: 'daniel.okafor@example.com',
          phone: '0423 778 219',
          moveInDate: '2025-09-01',
          bondPaid: true,
          bondAmount: 784,
          docVerified: true,
          advanceRentPaid: true,
          acceptedRulesAt: '2025-09-01T09:30:00.000',
          lifestyle: Lifestyle(
            smoking: 'outside-only',
            alcohol: 'social',
            drugs: 'occasionally',
            relationship: 'single',
            pets: 'none',
            schedule: 'flexible',
            guests: 'rarely',
            cleanliness: 'tidy',
            diet: 'none',
            occupation: 'Software engineer',
          ),
          emergency: EmergencyContact(name: 'Chidi Okafor', relationship: 'Brother', phone: '0423 110 887'),
          // Submitted, awaiting the admin's review.
          leaseVerification: LeaseVerification(
            fullName: 'Daniel Okafor',
            phone: '0423 778 219',
            email: 'daniel.okafor@example.com',
            agreement: Attachment(fileName: 'tenancy-agreement.pdf', type: 'application/pdf', size: 196000),
            status: 'pending',
            submittedAt: '2026-06-15T11:30:00.000',
          ),
        ),
        User(
          id: 'u3',
          name: 'Priya Sharma',
          initials: 'PS',
          role: 'tenant',
          email: 'priya.sharma@example.com',
          phone: '0431 902 564',
          moveInDate: '2025-09-15',
          bondPaid: true,
          bondAmount: 784,
          docVerified: true,
          advanceRentPaid: true,
          acceptedRulesAt: '2025-09-14T18:10:00.000',
          lifestyle: Lifestyle(
            smoking: 'non-smoker',
            alcohol: 'none',
            drugs: 'no',
            relationship: 'single',
            pets: 'none',
            schedule: 'early-bird',
            guests: 'rarely',
            cleanliness: 'very-tidy',
            diet: 'halal',
            occupation: 'Nurse',
          ),
          emergency: EmergencyContact(name: 'Anita Sharma', relationship: 'Mother', phone: '0431 552 109'),
          leaseholderUserId: 'u1',
          leaseholderName: 'Maya Chen',
        ),
        User(
          id: 'u4',
          name: 'Tom Becker',
          initials: 'TB',
          role: 'tenant',
          email: 'tom.becker@example.com',
          phone: '0438 145 770',
          moveInDate: '2025-10-01',
          bondPaid: true,
          bondAmount: 784,
          docVerified: true,
          advanceRentPaid: false,
          acceptedRulesAt: '2025-09-30T12:45:00.000',
          lifestyle: Lifestyle(
            smoking: 'non-smoker',
            alcohol: 'regular',
            drugs: 'occasionally',
            relationship: 'single',
            pets: 'has-pets',
            schedule: 'night-owl',
            guests: 'sometimes',
            cleanliness: 'average',
            diet: 'none',
            occupation: 'Engineering student',
          ),
          emergency: EmergencyContact(name: 'Lena Becker', relationship: 'Mother', phone: '0438 220 654'),
          leaseholderUserId: 'u1',
          leaseholderName: 'Maya Chen',
        ),
        User(
          id: 'u5',
          name: 'Aisha Rahman',
          initials: 'AR',
          role: 'tenant',
          email: 'aisha.rahman@example.com',
          phone: '0420 663 118',
          moveInDate: '2026-02-01',
          bondPaid: false,
          bondAmount: 784,
          docVerified: false,
          advanceRentPaid: false,
          pending: true,
        ),
      ];

  static List<Invite> invites() => [];
  static List<HouseRule> rules() => [];

  // A few demo bills, including saved payment records (by name + date) so the
  // "who paid, and when" history is visible the moment the demo loads.
  static List<Bill> bills() => [
        Bill(
          id: 'b1',
          title: 'Electricity — AGL (Mar–May)',
          category: 'utility',
          amount: 312.40,
          periodStart: '2026-03-01',
          periodEnd: '2026-05-31',
          dueDate: '2026-05-20',
          issuedBy: 'u1',
          split: 'equal',
          shares: {'u1': 78.10, 'u2': 78.10, 'u3': 78.10, 'u4': 78.10},
          status: 'settled',
          paidBy: {'u1': true, 'u2': true, 'u3': true, 'u4': true},
          payments: {
            'u1': Payment(payerId: 'u1', payerName: 'Maya Chen', at: '2026-05-16T09:24:00.000', amount: 78.10),
            'u2': Payment(payerId: 'u2', payerName: 'Daniel Okafor', at: '2026-05-17T18:02:00.000', amount: 78.10),
            'u3': Payment(payerId: 'u3', payerName: 'Priya Sharma', at: '2026-05-18T07:41:00.000', amount: 78.10),
            'u4': Payment(
                payerId: 'u4',
                payerName: 'Tom Becker',
                confirmedBy: 'Maya Chen',
                at: '2026-05-19T20:15:00.000',
                amount: 78.10),
          },
        ),
        Bill(
          id: 'b2',
          title: 'NBN internet — May',
          category: 'internet',
          amount: 89,
          periodStart: '2026-05-01',
          periodEnd: '2026-05-31',
          dueDate: '2026-05-28',
          issuedBy: 'u2',
          split: 'equal',
          shares: {'u1': 22.25, 'u2': 22.25, 'u3': 22.25, 'u4': 22.25},
          status: 'pending',
          paidBy: {'u1': true, 'u2': true, 'u3': true},
          payments: {
            'u1': Payment(payerId: 'u1', payerName: 'Maya Chen', at: '2026-05-26T10:05:00.000', amount: 22.25),
            'u2': Payment(payerId: 'u2', payerName: 'Daniel Okafor', at: '2026-05-26T12:30:00.000', amount: 22.25),
            'u3': Payment(payerId: 'u3', payerName: 'Priya Sharma', at: '2026-05-27T08:50:00.000', amount: 22.25),
          },
        ),
        Bill(
          id: 'b3',
          title: 'Water — Q1 (Sydney Water)',
          category: 'water',
          amount: 180,
          periodStart: '2026-03-01',
          periodEnd: '2026-05-31',
          dueDate: '2026-06-10',
          issuedBy: 'u1',
          split: 'equal',
          shares: {'u1': 45.00, 'u2': 45.00, 'u3': 45.00, 'u4': 45.00},
          status: 'pending',
        ),
      ];
  static List<BillSchedule> schedules() => [];
  static List<Subscription> subscriptions() => [];
  static List<Necessity> necessities() => [];
  static List<Grocery> groceries() => [];
  // Weekly cleaning roster — each housemate owns a day + area.
  static List<CleaningRosterEntry> roster() => [
        CleaningRosterEntry(day: 'Mon', area: 'Kitchen', assignee: 'u3'),
        CleaningRosterEntry(day: 'Wed', area: 'Bathrooms', assignee: 'u4'),
        CleaningRosterEntry(day: 'Fri', area: 'Common areas & floors', assignee: 'u1'),
        CleaningRosterEntry(day: 'Sun', area: 'Bins & recycling', assignee: 'u2'),
      ];

  static List<CleaningTask> tasks() => [
        CleaningTask(id: 'c1', task: 'Scrub the oven', assignee: 'u3', dueDate: daysAheadIso(2)),
        CleaningTask(id: 'c2', task: 'Vacuum the living room', assignee: 'u4', dueDate: daysAheadIso(1)),
        CleaningTask(id: 'c3', task: 'Wipe down the bathroom mirrors', assignee: 'u4', dueDate: daysAgoIso(1)),
      ];
  static List<Party> parties() => [];

  // A few demo posts in the group chat.
  static Messages messages() => Messages(
        group: [
          Message(
            id: 'm1',
            from: 'u1',
            text: 'Welcome to the house group chat everyone! 🏡 Please drop your details on the Housemates page when you get a sec.',
            at: '2025-09-15T19:02:00.000',
          ),
          Message(
            id: 'm2',
            from: 'u2',
            text: 'Bins go out Tuesday nights — red lid weekly, yellow lid fortnightly. I\'ll set a reminder on the cleaning roster.',
            at: '2025-09-16T08:24:00.000',
          ),
          Message(
            id: 'm3',
            from: 'u3',
            text: 'Thanks Maya! Just moved my stuff in, kitchen shelf on the left is mine 🙌',
            at: '2025-09-16T17:48:00.000',
          ),
          Message(
            id: 'm4',
            from: 'u4',
            text: 'Internet is up and running — NBN 100. Login details are on the fridge whiteboard.',
            at: '2025-10-02T11:15:00.000',
          ),
          Message(
            id: 'm5',
            from: 'u1',
            text: 'Quick one: who\'s around for a house dinner this Sunday? Thinking we split groceries and cook together 🍝',
            at: '2026-05-28T20:05:00.000',
          ),
          Message(
            id: 'm6',
            from: 'u5',
            text: 'Count me in! I can bring dessert 🍰',
            at: '2026-05-28T20:11:00.000',
          ),
        ],
        dms: {},
      );

  static List<Complaint> complaints() => [];
  static List<Issue> issues() => [];

  // Demo posts in the room/housemate marketplace — from both leaseholders
  // (advertising the spare room) and tenants (scouting their next place).
  static List<Listing> listings() => [
        Listing(
          id: 'l1',
          type: 'tenant-wanted',
          by: 'u1', // Maya (leaseholder)
          title: 'Sunny double room in our Marrickville terrace',
          suburb: 'Marrickville',
          rent: 290,
          availableFrom: '2026-06-15',
          description:
              'Big north-facing double in a friendly 4-bed terrace. Sharing with two tenants and a leaseholder — tidy, social but respectful. Walk to Marrickville Metro and the cafés on Illawarra Rd.',
          createdAt: '2026-05-30',
        ),
        Listing(
          id: 'l2',
          type: 'tenant-wanted',
          by: 'u2', // Daniel (leaseholder)
          title: 'Quiet room, 5 min walk to the station',
          suburb: 'Marrickville',
          rent: 270,
          availableFrom: '2026-07-01',
          description:
              'Cosy single room, perfect for someone who works from home. Quiet professional household, dishwasher, off-street parking and a sunny backyard.',
          createdAt: '2026-05-26',
        ),
        Listing(
          id: 'l3',
          type: 'room-wanted',
          by: 'u3', // Priya (tenant)
          title: 'Tidy nurse after a room in the inner west',
          suburb: 'Inner West',
          budget: 320,
          availableFrom: '2026-06-20',
          description:
              'Day-shift nurse, very clean and easy-going. Looking for a calm sharehouse near Marrickville or Dulwich Hill. Happy to share references from my current place.',
          createdAt: '2026-05-28',
        ),
        Listing(
          id: 'l4',
          type: 'room-wanted',
          by: 'u4', // Tom (tenant)
          title: 'Easy-going grad student looking for a room',
          suburb: 'Newtown / Marrickville',
          budget: 250,
          availableFrom: '2026-07-10',
          description:
              'Final-year engineering student, mostly on campus during the week. Tidy, love to cook, keen to find a sociable but laid-back house.',
          createdAt: '2026-05-22',
        ),
      ];

  static List<ListingInterest> listingInterests() => [];
  static List<Inspection> inspections() => [];

  // Demo in-post conversations across all four listings — leaseholders,
  // tenants, and a newcomer, including performance requests and shares.
  static List<PostMessage> postMessages() => [
        // ── l1 (Maya's room) × Priya ────────────────────────────────────────
        PostMessage(
          id: 'pm1',
          listingId: 'l1',
          from: 'u3', // Priya
          to: 'u1', // Maya
          text: 'Hi Maya! Your double room looks lovely — is it still free from mid-June?',
          at: '2026-05-31T09:12:00.000',
        ),
        PostMessage(
          id: 'pm2',
          listingId: 'l1',
          from: 'u1',
          to: 'u3',
          text: "Hi Priya! Yes, available from the 15th 🙂 The house is pretty tidy so we like to get a feel for how new housemates run things.",
          at: '2026-05-31T10:02:00.000',
        ),
        PostMessage(
          id: 'pm3',
          listingId: 'l1',
          from: 'u1',
          to: 'u3',
          kind: 'perf-request',
          text: 'Maya asked for your housemate track record.',
          at: '2026-05-31T10:03:00.000',
        ),
        PostMessage(
          id: 'pm4',
          listingId: 'l1',
          from: 'u3',
          to: 'u1',
          kind: 'perf-share',
          text: 'Happy to — here\'s my record from my current place.',
          at: '2026-05-31T10:20:00.000',
          perf: PerfSnapshot(
            standing: 92,
            band: 'Good',
            doneCount: 11,
            taskCount: 12,
            choreRate: 11 / 12,
            paidCount: 8,
            billCount: 8,
            billRate: 1.0,
            complaintSeverity: 0,
            partiesHosted: 1,
            house: '12 Marrickville Road, Marrickville NSW 2204',
            note: 'Always paid bills on time, zero complaints. Happy to give a phone reference too!',
          ),
        ),
        PostMessage(
          id: 'pm5',
          listingId: 'l1',
          from: 'u1',
          to: 'u3',
          text: "That's a great record Priya 🙌 Want to drop by Saturday arvo to see the place?",
          at: '2026-05-31T11:05:00.000',
        ),
        PostMessage(
          id: 'pm5b',
          listingId: 'l1',
          from: 'u3',
          to: 'u1',
          text: 'Saturday works perfectly — what time suits you?',
          at: '2026-05-31T11:22:00.000',
        ),
        PostMessage(
          id: 'pm5c',
          listingId: 'l1',
          from: 'u1',
          to: 'u3',
          text: '2 pm? I\'ll send you the address.',
          at: '2026-05-31T11:35:00.000',
        ),
        PostMessage(
          id: 'pm5d',
          listingId: 'l1',
          from: 'u1',
          to: 'u3',
          kind: 'inspection-invite',
          text: 'Maya invited you to inspect the room — Sat 15 Jun at 2:00 pm.',
          at: '2026-05-31T11:40:00.000',
        ),
        PostMessage(
          id: 'pm5e',
          listingId: 'l1',
          from: 'u3',
          to: 'u1',
          kind: 'inspection-confirm',
          text: 'Priya confirmed — see you Saturday at 2 pm!',
          at: '2026-05-31T11:58:00.000',
        ),
        PostMessage(
          id: 'pm5f',
          listingId: 'l1',
          from: 'u3',
          to: 'u1',
          text: 'Should I bring anything or just myself?',
          at: '2026-05-31T12:05:00.000',
        ),
        PostMessage(
          id: 'pm5g',
          listingId: 'l1',
          from: 'u1',
          to: 'u3',
          text: 'Just yourself! The other housemates will be home too so you can meet everyone. See you then 😊',
          at: '2026-05-31T12:18:00.000',
        ),

        // ── l1 (Maya's room) × Daniel — leaseholder vouches for Priya ────────
        PostMessage(
          id: 'pm_d1',
          listingId: 'l1',
          from: 'u2',
          to: 'u1',
          text: 'Hi Maya! Priya applied for our spare room and mentioned she lives at your place. Would you be comfortable sharing her reference through the app?',
          at: '2026-06-03T09:30:00.000',
        ),
        PostMessage(
          id: 'pm_d2',
          listingId: 'l1',
          from: 'u1',
          to: 'u2',
          text: 'Hey Daniel! Absolutely — Priya has been one of our best. Always on time, zero complaints, keeps things immaculate. Happy to vouch for her.',
          at: '2026-06-03T10:00:00.000',
        ),
        PostMessage(
          id: 'pm_d3',
          listingId: 'l1',
          from: 'u2',
          to: 'u1',
          kind: 'perf-request',
          text: 'Daniel asked about one of your tenants\' track record.',
          at: '2026-06-03T10:01:00.000',
        ),
        PostMessage(
          id: 'pm_d4',
          listingId: 'l1',
          from: 'u1',
          to: 'u2',
          kind: 'perf-share',
          text: 'Shared a reference for Priya Sharma.',
          at: '2026-06-03T10:08:00.000',
          perf: PerfSnapshot(
            standing: 92,
            band: 'Good',
            doneCount: 11,
            taskCount: 12,
            choreRate: 11 / 12,
            paidCount: 8,
            billCount: 8,
            billRate: 1.0,
            complaintSeverity: 0,
            partiesHosted: 1,
            house: '12 Marrickville Road, Marrickville NSW 2204',
            note: 'Priya has been an excellent housemate — prompt with payments, tidy, and very considerate. Would happily have her again.',
            subject: 'Priya Sharma',
          ),
        ),
        PostMessage(
          id: 'pm_d5',
          listingId: 'l1',
          from: 'u2',
          to: 'u1',
          text: 'Stellar reference — thanks so much Maya! This really helps. I\'ll get back to Priya today 🙏',
          at: '2026-06-03T10:15:00.000',
        ),

        // ── l1 (Maya's room) × Tom ───────────────────────────────────────────
        PostMessage(
          id: 'pm6',
          listingId: 'l1',
          from: 'u4', // Tom
          to: 'u1', // Maya
          text: 'Hey Maya! Is the double still up? I\'m studying nearby and the location is ideal.',
          at: '2026-06-01T08:45:00.000',
        ),
        PostMessage(
          id: 'pm6b',
          listingId: 'l1',
          from: 'u1',
          to: 'u4',
          text: 'Hi Tom! Still available 😊 We do like to see a reference before arranging a visit — would you be okay sharing your housemate record?',
          at: '2026-06-01T09:20:00.000',
        ),
        PostMessage(
          id: 'pm6c',
          listingId: 'l1',
          from: 'u1',
          to: 'u4',
          kind: 'perf-request',
          text: 'Maya asked for your housemate track record.',
          at: '2026-06-01T09:21:00.000',
        ),
        PostMessage(
          id: 'pm6d',
          listingId: 'l1',
          from: 'u4',
          to: 'u1',
          kind: 'perf-share',
          text: 'Sure, no worries — here it is.',
          at: '2026-06-01T10:05:00.000',
          perf: PerfSnapshot(
            standing: 74,
            band: 'Fair',
            doneCount: 7,
            taskCount: 10,
            choreRate: 0.7,
            paidCount: 5,
            billCount: 6,
            billRate: 5 / 6,
            complaintSeverity: 5,
            partiesHosted: 2,
            house: '8 Enmore Road, Newtown NSW 2042',
            note: 'Hosted two small gatherings — both wrapped by midnight. Working on my chore consistency!',
          ),
        ),
        PostMessage(
          id: 'pm6e',
          listingId: 'l1',
          from: 'u1',
          to: 'u4',
          text: 'Appreciate the honesty Tom 😄 The chore rate could be better but it\'s a fair score. I\'ll have a chat with the other housemates and get back to you.',
          at: '2026-06-01T10:40:00.000',
        ),

        // ── l2 (Daniel's room) × Tom ─────────────────────────────────────────
        PostMessage(
          id: 'pm7',
          listingId: 'l2',
          from: 'u4', // Tom
          to: 'u2', // Daniel
          text: 'Hey Daniel, is the quiet room still going? I work from home a couple of days so it sounds perfect.',
          at: '2026-05-27T14:30:00.000',
        ),
        PostMessage(
          id: 'pm7b',
          listingId: 'l2',
          from: 'u2',
          to: 'u4',
          text: 'Hey Tom! Still going 🙌 Tell me a bit about yourself — are you tidier than the average student? 😄',
          at: '2026-05-27T16:00:00.000',
        ),
        PostMessage(
          id: 'pm7c',
          listingId: 'l2',
          from: 'u4',
          to: 'u2',
          text: 'Ha — honestly yes. I cook a lot so the kitchen gets real use but I clean as I go. Dishes same day, wipe-down after every session.',
          at: '2026-05-27T16:30:00.000',
        ),
        PostMessage(
          id: 'pm7d',
          listingId: 'l2',
          from: 'u2',
          to: 'u4',
          kind: 'perf-request',
          text: 'Daniel asked for your housemate track record.',
          at: '2026-05-27T16:32:00.000',
        ),
        PostMessage(
          id: 'pm7e',
          listingId: 'l2',
          from: 'u4',
          to: 'u2',
          kind: 'perf-share',
          text: 'Here\'s my current record — full transparency.',
          at: '2026-05-27T17:10:00.000',
          perf: PerfSnapshot(
            standing: 74,
            band: 'Fair',
            doneCount: 7,
            taskCount: 10,
            choreRate: 0.7,
            paidCount: 5,
            billCount: 6,
            billRate: 5 / 6,
            complaintSeverity: 5,
            partiesHosted: 2,
            house: '8 Enmore Road, Newtown NSW 2042',
            note: 'Two parties on weekends, guests out by midnight. Bills mostly on time.',
          ),
        ),
        PostMessage(
          id: 'pm7f',
          listingId: 'l2',
          from: 'u2',
          to: 'u4',
          text: 'Appreciate the honesty! Parties are fine as long as they wrap up at a reasonable hour. Want to pop by Thursday evening to see the room?',
          at: '2026-05-27T17:45:00.000',
        ),
        PostMessage(
          id: 'pm7g',
          listingId: 'l2',
          from: 'u4',
          to: 'u2',
          text: 'Thursday works great — what time? 6 pm?',
          at: '2026-05-27T18:02:00.000',
        ),
        PostMessage(
          id: 'pm7h',
          listingId: 'l2',
          from: 'u2',
          to: 'u4',
          kind: 'inspection-invite',
          text: 'Daniel invited you to view the room — Thu 29 May at 6:00 pm.',
          at: '2026-05-27T18:10:00.000',
        ),
        PostMessage(
          id: 'pm7i',
          listingId: 'l2',
          from: 'u4',
          to: 'u2',
          kind: 'inspection-confirm',
          text: 'Tom confirmed — see you Thursday at 6!',
          at: '2026-05-27T18:22:00.000',
        ),
        PostMessage(
          id: 'pm7j',
          listingId: 'l2',
          from: 'u4',
          to: 'u2',
          text: 'Is there parking nearby or should I just take the train?',
          at: '2026-05-27T18:25:00.000',
        ),
        PostMessage(
          id: 'pm7k',
          listingId: 'l2',
          from: 'u2',
          to: 'u4',
          text: 'Train is easiest — two minutes from the station. I\'ll text you the street number on Thursday.',
          at: '2026-05-27T18:40:00.000',
        ),

        // ── l2 (Daniel's room) × Aisha (new/other) ───────────────────────────
        PostMessage(
          id: 'pm8',
          listingId: 'l2',
          from: 'u5', // Aisha — pending tenant, new to platform
          to: 'u2', // Daniel
          text: 'Hi Daniel! I\'m Aisha, relocating from Melbourne next month. Your listing looks exactly what I need — is it still available for July?',
          at: '2026-06-02T14:00:00.000',
        ),
        PostMessage(
          id: 'pm8b',
          listingId: 'l2',
          from: 'u2',
          to: 'u5',
          text: 'Hi Aisha! July 1st works 🙂 Do you have a housemate reference from your last place? We like to see a track record before arranging an inspection.',
          at: '2026-06-02T15:30:00.000',
        ),
        PostMessage(
          id: 'pm8c',
          listingId: 'l2',
          from: 'u2',
          to: 'u5',
          kind: 'perf-request',
          text: 'Daniel asked for your housemate track record.',
          at: '2026-06-02T15:31:00.000',
        ),
        PostMessage(
          id: 'pm8d',
          listingId: 'l2',
          from: 'u5',
          to: 'u2',
          text: 'I\'m new to Homies so I don\'t have an in-app record yet — but I have a written reference from my landlord in Melbourne. Happy to send that through?',
          at: '2026-06-02T16:10:00.000',
        ),
        PostMessage(
          id: 'pm8e',
          listingId: 'l2',
          from: 'u2',
          to: 'u5',
          text: 'That\'s totally fine — send it over and we\'ll take it from there. Once you settle in and use Homies for a while your record builds up automatically.',
          at: '2026-06-02T16:30:00.000',
        ),
        PostMessage(
          id: 'pm8f',
          listingId: 'l2',
          from: 'u5',
          to: 'u2',
          text: 'Sent! It\'s from my landlord of three years in Melbourne — glowing review 😊 Also happy to jump on a quick call if that helps.',
          at: '2026-06-02T17:00:00.000',
        ),
        PostMessage(
          id: 'pm8g',
          listingId: 'l2',
          from: 'u2',
          to: 'u5',
          text: 'Love the enthusiasm Aisha! Reference looks great. Would you be up for a quick inspection next week so you can see the place before committing?',
          at: '2026-06-03T09:00:00.000',
        ),
        PostMessage(
          id: 'pm8h',
          listingId: 'l2',
          from: 'u5',
          to: 'u2',
          text: 'Yes absolutely — I\'m flexible most days next week after 4 pm.',
          at: '2026-06-03T09:20:00.000',
        ),
        PostMessage(
          id: 'pm8i',
          listingId: 'l2',
          from: 'u2',
          to: 'u5',
          kind: 'inspection-invite',
          text: 'Daniel invited you to view the room — Wed 10 Jun at 5:30 pm.',
          at: '2026-06-03T09:35:00.000',
        ),
        PostMessage(
          id: 'pm8j',
          listingId: 'l2',
          from: 'u5',
          to: 'u2',
          kind: 'inspection-confirm',
          text: 'Aisha confirmed — can\'t wait, thank you Daniel!',
          at: '2026-06-03T09:50:00.000',
        ),

        // ── l3 (Priya's room-wanted) × Daniel ────────────────────────────────
        PostMessage(
          id: 'pm9',
          listingId: 'l3',
          from: 'u2', // Daniel (leaseholder reaching out to tenant's post)
          to: 'u3', // Priya (poster)
          text: 'Hi Priya! I\'m Daniel — we have a quiet single opening July 1st, five minutes from Marrickville station. Could be a great fit for you?',
          at: '2026-05-29T11:00:00.000',
        ),
        PostMessage(
          id: 'pm9b',
          listingId: 'l3',
          from: 'u3',
          to: 'u2',
          text: 'Hi Daniel! July 1st is perfect — I finish my current lease June 30. Is the room furnished at all?',
          at: '2026-05-29T11:45:00.000',
        ),
        PostMessage(
          id: 'pm9c',
          listingId: 'l3',
          from: 'u2',
          to: 'u3',
          text: 'Semi-furnished — bed frame and mattress included, the rest is yours to make home. The house is quiet professionals, very tidy. Would you be able to share your housemate reference?',
          at: '2026-05-29T12:20:00.000',
        ),
        PostMessage(
          id: 'pm9d',
          listingId: 'l3',
          from: 'u2',
          to: 'u3',
          kind: 'perf-request',
          text: 'Daniel asked for your housemate track record.',
          at: '2026-05-29T12:21:00.000',
        ),
        PostMessage(
          id: 'pm9e',
          listingId: 'l3',
          from: 'u3',
          to: 'u2',
          kind: 'perf-share',
          text: 'Of course — here\'s my full record.',
          at: '2026-05-29T13:00:00.000',
          perf: PerfSnapshot(
            standing: 92,
            band: 'Good',
            doneCount: 11,
            taskCount: 12,
            choreRate: 11 / 12,
            paidCount: 8,
            billCount: 8,
            billRate: 1.0,
            complaintSeverity: 0,
            partiesHosted: 1,
            house: '12 Marrickville Road, Marrickville NSW 2204',
            note: 'No complaints ever, all bills on time. Early riser so I keep things quiet in the mornings.',
          ),
        ),
        PostMessage(
          id: 'pm9f',
          listingId: 'l3',
          from: 'u2',
          to: 'u3',
          text: 'That\'s an excellent record Priya! Let\'s arrange a visit — are you free this weekend to come see the place?',
          at: '2026-05-29T13:30:00.000',
        ),
        PostMessage(
          id: 'pm9g',
          listingId: 'l3',
          from: 'u3',
          to: 'u2',
          text: 'Sunday afternoon works for me! Looking forward to it 😊',
          at: '2026-05-29T13:45:00.000',
        ),
        PostMessage(
          id: 'pm9h',
          listingId: 'l3',
          from: 'u2',
          to: 'u3',
          kind: 'inspection-invite',
          text: 'Daniel invited you to view the room — Sun 1 Jun at 3:00 pm.',
          at: '2026-05-29T14:00:00.000',
        ),
        PostMessage(
          id: 'pm9i',
          listingId: 'l3',
          from: 'u3',
          to: 'u2',
          kind: 'inspection-confirm',
          text: 'Priya confirmed the inspection — see you Sunday!',
          at: '2026-05-29T14:12:00.000',
        ),
        PostMessage(
          id: 'pm9j',
          listingId: 'l3',
          from: 'u3',
          to: 'u2',
          text: 'Quick question — is the room on the ground floor or upstairs? I have a lot of boxes to move in!',
          at: '2026-05-29T14:15:00.000',
        ),
        PostMessage(
          id: 'pm9k',
          listingId: 'l3',
          from: 'u2',
          to: 'u3',
          text: 'Second floor, but we have a solid freight lift in the building so moving in is actually really easy. See you Sunday!',
          at: '2026-05-29T14:28:00.000',
        ),

        // ── l4 (Tom's room-wanted) × Maya ────────────────────────────────────
        PostMessage(
          id: 'pm10',
          listingId: 'l4',
          from: 'u1', // Maya (leaseholder reaching out to tenant's post)
          to: 'u4', // Tom (poster)
          text: 'Hi Tom! We have a big north-facing double going in Marrickville — \$290/wk, social house, walk to the Metro. Interested?',
          at: '2026-05-23T09:00:00.000',
        ),
        PostMessage(
          id: 'pm10b',
          listingId: 'l4',
          from: 'u4',
          to: 'u1',
          text: 'Hey Maya! That sounds perfect — the location is exactly right. What are the other housemates like?',
          at: '2026-05-23T09:30:00.000',
        ),
        PostMessage(
          id: 'pm10c',
          listingId: 'l4',
          from: 'u1',
          to: 'u4',
          text: 'Two leaseholders and two tenants — tidy, sociable but pretty low-key. We do like to check references before inspections though. Would you be okay sharing your housemate record?',
          at: '2026-05-23T10:05:00.000',
        ),
        PostMessage(
          id: 'pm10d',
          listingId: 'l4',
          from: 'u1',
          to: 'u4',
          kind: 'perf-request',
          text: 'Maya asked for your housemate track record.',
          at: '2026-05-23T10:06:00.000',
        ),
        PostMessage(
          id: 'pm10e',
          listingId: 'l4',
          from: 'u4',
          to: 'u1',
          kind: 'perf-share',
          text: 'No worries — I like being upfront.',
          at: '2026-05-23T10:55:00.000',
          perf: PerfSnapshot(
            standing: 74,
            band: 'Fair',
            doneCount: 7,
            taskCount: 10,
            choreRate: 0.7,
            paidCount: 5,
            billCount: 6,
            billRate: 5 / 6,
            complaintSeverity: 5,
            partiesHosted: 2,
            house: '8 Enmore Road, Newtown NSW 2042',
            note: 'Not perfect but never missed rent. Parties are always weekend and wrapped by midnight.',
          ),
        ),
        PostMessage(
          id: 'pm10f',
          listingId: 'l4',
          from: 'u1',
          to: 'u4',
          text: 'Thanks Tom — appreciate the candour! Fair score, definitely workable. I\'ll loop in our other housemate and we\'ll sort a time 🙌',
          at: '2026-05-23T11:20:00.000',
        ),
        PostMessage(
          id: 'pm10g',
          listingId: 'l4',
          from: 'u4',
          to: 'u1',
          text: 'No rush — take your time. I\'m flexible on weekends mostly.',
          at: '2026-05-23T11:35:00.000',
        ),
        PostMessage(
          id: 'pm10h',
          listingId: 'l4',
          from: 'u1',
          to: 'u4',
          text: 'Daniel is keen too — we\'re both happy to show you around. How does Saturday 7 June sound?',
          at: '2026-05-25T09:00:00.000',
        ),
        PostMessage(
          id: 'pm10i',
          listingId: 'l4',
          from: 'u4',
          to: 'u1',
          text: 'Saturday 7th is perfect for me! Morning or arvo?',
          at: '2026-05-25T09:45:00.000',
        ),
        PostMessage(
          id: 'pm10j',
          listingId: 'l4',
          from: 'u1',
          to: 'u4',
          kind: 'inspection-invite',
          text: 'Maya invited you to view the room — Sat 7 Jun at 11:00 am.',
          at: '2026-05-25T10:00:00.000',
        ),
        PostMessage(
          id: 'pm10k',
          listingId: 'l4',
          from: 'u4',
          to: 'u1',
          kind: 'inspection-confirm',
          text: 'Tom confirmed — see you Saturday at 11 am! Really looking forward to it.',
          at: '2026-05-25T10:10:00.000',
        ),
      ];

  // Rent is $980/wk split equally among 4 housemates = $245/person.
  // Rent week starts every Monday from 2025-09-01 (Sep 1 = Mon).
  // Current week: 2026-06-22. u1+u2 paid; u3+u4 still outstanding.
  static List<RentPayment> rentPayments() => [
        // Current period – week of 22 Jun 2026
        RentPayment(id: 'rp1', userId: 'u1', userName: 'Maya Chen',    amount: 245, paidAt: '2026-06-22T08:30:00.000', periodStart: '2026-06-22'),
        RentPayment(id: 'rp2', userId: 'u2', userName: 'Daniel Okafor', amount: 245, paidAt: '2026-06-22T09:15:00.000', periodStart: '2026-06-22'),
        // Previous period – week of 15 Jun 2026
        RentPayment(id: 'rp3', userId: 'u1', userName: 'Maya Chen',    amount: 245, paidAt: '2026-06-15T08:00:00.000', periodStart: '2026-06-15'),
        RentPayment(id: 'rp4', userId: 'u2', userName: 'Daniel Okafor', amount: 245, paidAt: '2026-06-15T09:00:00.000', periodStart: '2026-06-15'),
        RentPayment(id: 'rp5', userId: 'u3', userName: 'Priya Sharma',  amount: 245, paidAt: '2026-06-15T10:30:00.000', periodStart: '2026-06-15'),
        RentPayment(id: 'rp6', userId: 'u4', userName: 'Tom Becker',    amount: 245, paidAt: '2026-06-16T11:00:00.000', periodStart: '2026-06-15'),
        // Two periods ago – week of 8 Jun 2026
        RentPayment(id: 'rp7',  userId: 'u1', userName: 'Maya Chen',    amount: 245, paidAt: '2026-06-08T08:00:00.000', periodStart: '2026-06-08'),
        RentPayment(id: 'rp8',  userId: 'u2', userName: 'Daniel Okafor', amount: 245, paidAt: '2026-06-08T09:00:00.000', periodStart: '2026-06-08'),
        RentPayment(id: 'rp9',  userId: 'u3', userName: 'Priya Sharma',  amount: 245, paidAt: '2026-06-08T10:00:00.000', periodStart: '2026-06-08'),
        RentPayment(id: 'rp10', userId: 'u4', userName: 'Tom Becker',    amount: 245, paidAt: '2026-06-09T12:00:00.000', periodStart: '2026-06-08'),
      ];

  static List<PersonalExpense> personalExpenses() => [
        PersonalExpense(
          id: 'pe1',
          userId: 'u1',
          category: 'grocery',
          title: 'Woolworths — personal groceries',
          amount: 47.50,
          date: '2026-06-22',
          note: 'Weekly shop for myself',
        ),
        PersonalExpense(
          id: 'pe2',
          userId: 'u1',
          category: 'subscription',
          title: 'iCloud Storage (200 GB)',
          amount: 1.49,
          date: '2026-06-15',
        ),
        PersonalExpense(
          id: 'pe3',
          userId: 'u1',
          category: 'other',
          title: 'Phone case',
          amount: 24.99,
          date: '2026-06-10',
        ),
        PersonalExpense(
          id: 'pe4',
          userId: 'u1',
          category: 'grocery',
          title: 'Harris Farm — coffee & snacks',
          amount: 18.50,
          date: '2026-06-08',
        ),
        PersonalExpense(
          id: 'pe5',
          userId: 'u1',
          category: 'necessity',
          title: 'Personal toiletries',
          amount: 32.80,
          date: '2026-05-29',
        ),
      ];

  static List<ChoreSwapRequest> choreSwaps() => [
        // Priya can't do her oven task — open to anyone
        ChoreSwapRequest(
          id: 'sw1',
          taskId: 'c1',
          fromUserId: 'u3',
          fromUserName: 'Priya Sharma',
          toUserId: null, // open to any housemate
          note: "I'll be out of town that day",
          requestedAt: '2026-06-23T18:00:00.000',
        ),
        // Tom asks Maya specifically to take his vacuum task
        ChoreSwapRequest(
          id: 'sw2',
          taskId: 'c2',
          fromUserId: 'u4',
          fromUserName: 'Tom Becker',
          toUserId: 'u1',
          toUserName: 'Maya Chen',
          note: 'Working a late shift',
          requestedAt: '2026-06-23T20:30:00.000',
        ),
      ];

  static List<MaintenanceContact> maintenanceContacts() => [
        MaintenanceContact(
          id: 'mc1',
          name: 'Emergency services',
          category: 'emergency',
          phone: '000',
          notes: 'Police, fire, ambulance. For life-threatening situations only.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc2',
          name: 'SES (State Emergency Service)',
          category: 'emergency',
          phone: '132 500',
          notes: 'Flood, storm, tree damage. Available 24/7.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc3',
          name: 'Harbourside Property Group',
          category: 'property',
          phone: '02 9555 1200',
          email: 'lettings@harbourside.com.au',
          notes: 'Our property management agency. For lease queries, inspections, and urgent repairs.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc4',
          name: 'Jake\'s Plumbing',
          category: 'trades',
          phone: '0412 334 501',
          email: 'jake@jakesplumbing.com.au',
          notes: 'Our go-to plumber. Available Mon–Sat. Call before 5 pm.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc5',
          name: 'Bright Spark Electrical',
          category: 'trades',
          phone: '0421 778 922',
          notes: 'Licensed electrician. Mention "Homies resident" for priority booking.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc6',
          name: 'Origin Energy (Gas)',
          category: 'utilities',
          phone: '132 461',
          email: 'help@originenergy.com.au',
          notes: 'Account #: 8842-7713. For gas outages or billing queries.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc7',
          name: 'Sydney Water',
          category: 'utilities',
          phone: '13 20 92',
          notes: 'Report water outages or leaks. Available 24/7.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
        MaintenanceContact(
          id: 'mc8',
          name: 'Aussie Broadband (NBN)',
          category: 'utilities',
          phone: '1300 880 905',
          notes: 'Our internet provider. Account under Maya Chen. Reference: ABB-449821.',
          addedBy: 'u1',
          addedAt: '2026-01-01T00:00:00.000',
        ),
      ];

  static WelcomeGuide welcomeGuide() => WelcomeGuide(
        message:
            "Welcome to our home! We're so glad you're here. This guide has everything you need to settle in — read through at your own pace, and don't hesitate to ask any of us if you have questions.",
        sections: [
          WelcomeSection(
            id: 'wg1',
            icon: '📶',
            title: 'WiFi',
            content: 'Network: Homies5G\nPassword: welcome2024!\n\nThere\'s also a guest network (Homies-Guest, no password) for visitors.',
          ),
          WelcomeSection(
            id: 'wg2',
            icon: '🗑️',
            title: 'Bins & recycling',
            content: 'Yellow lid (recycling) goes out Sunday night.\nGreen lid (general waste) goes out every second Sunday.\n\nPlease rinse containers before recycling. No food scraps in the yellow bin.',
          ),
          WelcomeSection(
            id: 'wg3',
            icon: '🚗',
            title: 'Parking',
            content: 'One spot per room in the driveway — first in, first served.\nVisitors can park on the street (free, 2-hour limit on weekdays).',
          ),
          WelcomeSection(
            id: 'wg4',
            icon: '🔑',
            title: 'Keys & access',
            content: 'You\'ve been given 2 keys. Please don\'t copy them without asking.\nFront door code: 4821. Always double-lock the deadbolt when leaving.',
          ),
          WelcomeSection(
            id: 'wg5',
            icon: '🛒',
            title: 'Nearby shops',
            content: 'Woolworths — 5 min walk on King St (open 7am–9pm).\n7-Eleven — 2 min on Park Ave (24h).\nFarmers market — every Saturday 8am–1pm on Wilson Square.',
          ),
          WelcomeSection(
            id: 'wg6',
            icon: '🚌',
            title: 'Getting around',
            content: 'Bus stop (Route 412 → City) — 2 min walk at the corner.\nCentral Station — 10 min on the 412.\nUber/Lyft pickup works well on King St.',
          ),
        ],
      );

  static List<ShoppingItem> shoppingList() => [
        ShoppingItem(id: 'si1', text: 'Milk (2L)', addedBy: 'u3', addedByName: 'Priya Sharma', addedAt: '2026-06-24T08:00:00.000'),
        ShoppingItem(id: 'si2', text: 'Bread', addedBy: 'u4', addedByName: 'Tom Becker', addedAt: '2026-06-24T09:30:00.000'),
        ShoppingItem(id: 'si3', text: 'Coffee beans', addedBy: 'u2', addedByName: 'Daniel Okafor', addedAt: '2026-06-23T21:00:00.000'),
        ShoppingItem(id: 'si4', text: 'Toilet paper (12-pack)', addedBy: 'u1', addedByName: 'Maya Chen', addedAt: '2026-06-23T20:15:00.000'),
        ShoppingItem(
          id: 'si5',
          text: 'Dish soap',
          addedBy: 'u1',
          addedByName: 'Maya Chen',
          addedAt: '2026-06-22T15:00:00.000',
          done: true,
          doneBy: 'u2',
          doneByName: 'Daniel Okafor',
          doneAt: '2026-06-23T11:30:00.000',
        ),
      ];
}
