// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGmicnf0KWs8qy_G8CzNmKgYHiDoasTBs',
    appId: '1:451958522457:web:ba8e24b47124aff03ce748',
    messagingSenderId: '451958522457',
    projectId: 'leasely-a11e4',
    authDomain: 'leasely-a11e4.firebaseapp.com',
    storageBucket: 'leasely-a11e4.firebasestorage.app',
    measurementId: 'G-6PDFE6QT4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhPDiNVG3U2mmpN-BvEkhtAxvx7eyTV-8',
    appId: '1:451958522457:android:210baefe0782d2bf3ce748',
    messagingSenderId: '451958522457',
    projectId: 'leasely-a11e4',
    storageBucket: 'leasely-a11e4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ZxrelXUnYmhSStd9hUaBTK83MnYAI2U',
    appId: '1:451958522457:ios:62b25f4458cce40b3ce748',
    messagingSenderId: '451958522457',
    projectId: 'leasely-a11e4',
    storageBucket: 'leasely-a11e4.firebasestorage.app',
    iosBundleId: 'com.leasely.mobile',
  );
}
