// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GvJX4pEekU9f8cNLKXVfrRsJjMhUKlE',
    appId: '1:579052656220:web:aeb7db0d4332218b307899',
    messagingSenderId: '579052656220',
    projectId: 'homies-980c7',
    authDomain: 'homies-980c7.firebaseapp.com',
    storageBucket: 'homies-980c7.firebasestorage.app',
    measurementId: 'G-0WZPLJW4ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkFHMhK3zSeYlutpEr_UDEfiYcCTtXhU',
    appId: '1:579052656220:android:c39c7bed528ae79e307899',
    messagingSenderId: '579052656220',
    projectId: 'homies-980c7',
    storageBucket: 'homies-980c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8z2vz3GeyPst9varMX1QmtOeFNeu-vCM',
    appId: '1:579052656220:ios:9887f57009c9b4f9307899',
    messagingSenderId: '579052656220',
    projectId: 'homies-980c7',
    storageBucket: 'homies-980c7.firebasestorage.app',
    iosBundleId: 'au.com.creyeti.homiesMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1GvJX4pEekU9f8cNLKXVfrRsJjMhUKlE',
    appId: '1:579052656220:web:a18cf6eb2bed6b95307899',
    messagingSenderId: '579052656220',
    projectId: 'homies-980c7',
    authDomain: 'homies-980c7.firebaseapp.com',
    storageBucket: 'homies-980c7.firebasestorage.app',
    measurementId: 'G-KQFHRQJRY3',
  );
}
